### ISSUE TITLE
lattice_tools not found erro

### ISSUE THREAD

**Issue by xslittlegrass** [allevitan/Band-Structure#1]
Thanks for sharing, it's very helpful.

I was trying to run the program but get an error says that the lattice_tools module not found.

should the line 4 in standards.py 

from lattice_tools import fermi_energy, bravais_lattice, reciprocal_vectors

be

from solvers.lattice_tools import fermi_energy, bravais_lattice, reciprocal_vectors

instead?

**Comment by allevitan** [comment]
Yep, absolutely. Had the fix on my local copy, have been dillydallying on the commit. Should be fixed now.
