### ISSUE TITLE
Question about Silicon example?

### ISSUE THREAD

**Issue by xslittlegrass** [allevitan/Band-Structure#2]
I found your package very helpful to demonstate otherwise difficult to understand 3D band structure. Hope you could keep updating. Thanks a lot.

I noticed that the "primitive transforms" in the silicon example has a different order than that in the diamond example, although they have similar crystal structures. I guess the order in the diamond example would be correct, right? By the way, why does the calculated band structure depend on the order of the primitive transforms?

**Comment by allevitan** [comment]
The result shouldn't depend on the order of the primitive transforms - it may be simply that the "viewer" is viewing the result along a different rlv when the order changes. The fermi energy is currently calculated in the viewer, and does depend upon what vector the viewer is using (although the real fermi energy, of course, does not.

It definitely could be the result of an undiagnosed bug in the solver, however (although the solver's method is not tuned to produce trustworthy results at all, it shouldn't produce results that depend on the order of the primitive transforms). I think the best diagnosis would come from building a more complete viewer program that could pinpoint the trouble.

**Comment by xslittlegrass** [comment]
By the way, where did you find the crystal structure information? For example, how can I find the values in "atoms", "lattice constants" and "primitive transforms" in the example files for other common material? Are you aware of some database that has these information? Thanks.
